- name: Include ../../vars/om-vars.yaml written by terraform during deployment
  include_vars:
    file: vars/om-vars.yaml

- name: Download .deb
  vars:
    urls:
      om_6_0_0: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.0.100.20220711T2119Z.amd64.deb
      om_6_0_1: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.1.100.20220720T1207Z.amd64.deb
      om_6_0_2: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.2.100.20220802T0955Z.amd64.deb
      om_6_0_3: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.3.100.20220830T1645Z.amd64.deb
      om_6_0_4: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.4.100.20221007T1747Z.amd64.deb
      om_6_0_5: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.5.100.20221019T1057Z.amd64.deb
      om_6_0_6: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.6.100.20221102T1837Z.amd64.deb
      om_6_0_7: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.7.100.20221129T1444Z.amd64.deb
      om_6_0_8: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.8.100.20230111T1647Z.amd64.deb
      om_6_0_9: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.9.100.20230201T2148Z.amd64.deb
      om_6_0_10: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.10.100.20230228T0343Z.amd64.deb
      om_6_0_11: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.11.100.20230310T0141Z.amd64.deb
      om_6_0_12: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.12.100.20230406T1856Z.amd64.deb
      om_6_0_13: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.13.100.20230502T1610Z.amd64.deb
      om_6_0_14: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.14.100.20230530T1837Z.amd64.deb
      om_6_0_15: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.15.100.20230614T1851Z.amd64.deb
      om_6_0_16: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.16.100.20230705T1544Z.amd64.deb
      om_6_0_17: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.17.100.20230801T1349Z.amd64.deb
      om_6_0_18: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.18.100.20230905T1424Z.amd64.deb
      om_6_0_19: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.19.100.20231002T1347Z.amd64.deb
      om_6_0_20: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.20.100.20231102T2125Z.amd64.deb
      om_6_0_21: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.21.100.20231213T1202Z.amd64.deb
      om_6_0_22: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.22.100.20231229T1643Z.amd64.deb
      om_6_0_23: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.23.100.20240402T1833Z.amd64.deb
      om_6_0_24: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.24.100.20240712T1254Z.amd64.deb
      om_6_0_latest: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-6.0.24.100.20240712T1254Z.amd64.deb
      om_7_0_0: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.0.500.20231218T1951Z.amd64.deb
      om_7_0_1: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.1.500.20240105T0224Z.amd64.deb
      om_7_0_2: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.2.500.20240130T2116Z.amd64.deb
      om_7_0_3: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.3.500.20240305T1916Z.amd64.deb
      om_7_0_4: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.4.500.20240405T1424Z.amd64.deb
      # removed from downloads  
      om_7_0_6: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.6.500.20240509T1421Z.amd64.deb
      om_7_0_7: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.7.500.20240605T1843Z.amd64.deb
      om_7_0_8: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.8.500.20240627T1700Z.amd64.deb
      om_7_0_9: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.9.500.20240716T1711Z.amd64.deb
      om_7_0_10: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.10.500.20240731T2147Z.amd64.deb
      om_7_0_latest: https://downloads.mongodb.com/on-prem-mms/deb/mongodb-mms-7.0.10.500.20240731T2147Z.amd64.deb
    om_download_url: "{{ urls[version] }}"
  get_url:
    url: "{{ om_download_url }}"
    dest: /home/ubuntu/mongodb-mms-{{version}}.deb
    mode: '0440'

- name: Stop mongodb-mms if exists
  become: true
  become_user: root
  shell: if systemctl is-enabled --quiet mongodb-mms; then systemctl stop mongodb-mms && echo stopped; fi
  register: output
  changed_when: "'stopped' in output.stdout"

- name: "Ubuntu, Install a deb via apt"
  become: true
  become_user: root
  apt:
    deb: /home/ubuntu/mongodb-mms-{{version}}.deb

- name: Replace a localhost appdb with our own
  become: true
  become_user: root
  lineinfile:
    path: /opt/mongodb/mms/conf/conf-mms.properties
    regexp: '^mongo.mongoUri'
    line: mongo.mongoUri=mongodb://{{appdb.0}}:27017/
  vars:
    HOST_COUNT: "{{ groups['amd64_backing_appdb'] | length }}"
  when: "HOST_COUNT | int == 1" # Standalone

- name: Replace a localhost appdb with our own
  become: true
  become_user: root
  lineinfile:
    path: /opt/mongodb/mms/conf/conf-mms.properties
    regexp: '^mongo.mongoUri'
    line: mongo.mongoUri=mongodb://{{appdb.0}}:27017,{{appdb.1}}:27017,{{appdb.2}}:27017/
  vars:
    HOST_COUNT: "{{ groups['amd64_backing_appdb'] | length }}"
  when: "HOST_COUNT | int == 3" # Replica Set

- name: Add settings to /opt/mongodb/mms/conf/conf-mms.properties
  become: true
  become_user: root
  blockinfile:
    path: /opt/mongodb/mms/conf/conf-mms.properties
    block: |
      {{ item.setting }}={{ item.value }}
    marker: "# Instance Parameter Overrides"
  loop:
    - { setting: mms.ignoreInitialUiSetup, value: "true" }
    - { setting: mms.centralUrl, value: "{{om_url.0}}" }
    # - { setting: automation.versions.source, value: mongodb }
    - { setting: mms.adminEmailAddr, value: no-reply@opsmanager.local }
    - { setting: mms.fromEmailAddr, value: no-reply@opsmanager.local }
    - { setting: mms.replyToEmailAddr, value: no-reply@opsmanager.local }
    - { setting: mms.mail.hostname, value: localhost }
    - { setting: mms.mail.port, value: "25" }
    - { setting: mms.mail.ssl, value: "true" }
    - { setting: mms.mail.transport, value: smtp }
    - { setting: mms.minimumTLSVersion, value: TLSv1.2 }
    - { setting: backup.forceWtSnapshot, value: "true" }
    - { setting: backup.forceSnapshot, value: "true" }

- name: Add LDAP settings to /opt/mongodb/mms/conf/conf-mms.properties
  become: true
  become_user: root
  blockinfile:
    path: /opt/mongodb/mms/conf/conf-mms.properties
    block: |
      {{ item.setting }}={{ item.value }}
    marker: "# Instance Parameter Overrides"
  loop:
    - { setting: mms.userSvcClass, value: com.xgen.svc.mms.svc.user.UserSvcLdap }
    - { setting: mms.ldap.url, value: "ldap://{{services_private.0}}:389" }
    - { setting: mms.ldap.bindDn, value: 'uid\=admin,cn\=users,cn\=accounts,dc\=idm,dc\=example,dc\=com' }
    - { setting: mms.ldap.bindPassword, value: password }
    - { setting: mms.ldap.user.baseDn, value: 'cn\=users,cn\=accounts,dc\=idm,dc=\example,dc\=com' }
    - { setting: mms.ldap.user.searchAttribute, value: mail }
    - { setting: mms.ldap.user.group, value: memberOf }
    - { setting: mms.ldap.global.role.owner, value: 'cn\=mmsglobaladmin,cn\=groups,cn\=accounts,dc\=idm,dc\=example,dc\=com'  }
    - { setting: mms.ldap.user.email, value: mail }
    - { setting: mms.ldap.user.firstName, value: givenName }
    - { setting: mms.ldap.user.lastName, value: sn }
  when: ldap == "true"

- name: "Enable mongodb-mms service"
  become: true
  become_user: root
  service:
    name: mongodb-mms
    enabled: yes

- name: "Start mongodb-mms"
  become: true
  become_user: root
  service: name=mongodb-mms state=started

